/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Servlet_Guice_JPA_SimpleForm;

import org.junit.Test;


public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    //    Library classUnderTest = new Library();
    //    assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
